apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: invoices
  labels:
    app: invoices
    component: app
spec:
  selector:
    app: invoices
    component: app
  ports:
    - port: 80
      targetPort: 80
